server:
  port: 8701

#指定当前eureka客户端的注册地址
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8503/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: eureka-provide
  security:
    user:
      name: admin
      password: admin
  cloud:
    loadbalancer:
      retry:
        enabled: false